import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { auth, db } from "./firebase.js";
import { enforceFJMCDeviceRule } from "./device-guard.js";
const q=new URLSearchParams(location.search), testId=q.get("test");
const titleEl=document.getElementById("testTitle"), metaEl=document.getElementById("testMeta"), area=document.getElementById("testArea");
document.getElementById("backBtn")?.addEventListener("click",()=>history.back());
document.getElementById("logoutBtn")?.addEventListener("click",async()=>{await signOut(auth);location.href="login.html";});
let test=null,user=null,timer=null,seconds=0,started=false;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
async function finish(){ if(!started)return; started=false; clearInterval(timer); const answers={}; document.querySelectorAll("input[type=radio]:checked").forEach(x=>answers[x.name]=Number(x.value)); let score=0;(test.questions||[]).forEach((x,i)=>{if(answers[`q${i}`]===Number(x.correct))score++;}); const result={name:user.displayName||user.email,email:user.email,uid:user.uid,testId,seriesId:test.seriesId,score,total:(test.questions||[]).length,percentage:(test.questions?.length?score/test.questions.length*100:0),answers,submittedAt:new Date().toISOString()}; try{await setDoc(doc(db,"testSeriesResults",`${testId}_${user.uid}`),result,{merge:true});}catch(e){console.error(e);} area.innerHTML=`<div style="text-align:center;padding:30px"><h2>Test Submitted</h2><h3>${score} / ${result.total}</h3><p>${result.percentage.toFixed(2)}%</p><button class="btn primary" onclick="history.back()">Back</button></div>`;}
async function start(){ if(!test){area.innerHTML="<p>Test not found.</p>";return;} titleEl.textContent=test.title||"Test Series Test"; metaEl.textContent=`${test.subject||""} • ${test.duration||30} minutes`;
let html=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><strong id="timer">00:00</strong><button id="submitTest" class="btn primary">Submit Test</button></div><hr>`;
(test.questions||[]).forEach((x,i)=>{html+=`<div class="card" style="margin:15px 0"><h3>Q${i+1}. ${esc(x.question)}</h3>${(x.options||[]).map((o,j)=>`<label style="display:block;margin:8px 0"><input type="radio" name="q${i}" value="${j}"> ${esc(o)}</label>`).join("")}</div>`}); area.innerHTML=html;document.getElementById("submitTest").onclick=finish;seconds=Number(test.duration||30)*60;started=true;const tick=()=>{const m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");document.getElementById("timer").textContent=`${m}:${s}`;if(seconds<=0)finish();else seconds--;};tick();timer=setInterval(tick,1000);}
onAuthStateChanged(auth,async u=>{if(!u){location.href=`login.html?redirect=${encodeURIComponent(location.href)}`;return;}user=u;try{if(!(await enforceFJMCDeviceRule(db,u))){await signOut(auth);location.href="login.html";return;}const snap=await getDoc(doc(db,"testSeriesTests",testId));if(snap.exists())test=snap.data();else test=null;start();}catch(e){console.error(e);area.innerHTML=`<p>${esc(e.message||"Unable to load test")}</p>`;}});
